import { reactRouter } from "@react-router/dev/vite";
import path from "path";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  ssr: {
    noExternal: [
      "@adobe/react-spectrum",
      "@react-spectrum/accordion",
      "@react-spectrum/actionbar",
      "@react-spectrum/actiongroup",
      "@react-spectrum/avatar",
      "@react-spectrum/badge",
      "@react-spectrum/breadcrumbs",
      "@react-spectrum/button",
      "@react-spectrum/buttongroup",
      "@react-spectrum/calendar",
      "@react-spectrum/checkbox",
      "@react-spectrum/combobox",
      "@react-spectrum/color",
      "@react-spectrum/contextualhelp",
      "@react-spectrum/datepicker",
      "@react-spectrum/dialog",
      "@react-spectrum/divider",
      "@react-spectrum/dnd",
      "@react-spectrum/dropzone",
      "@react-spectrum/form",
      "@react-spectrum/icon",
      "@react-spectrum/illustratedmessage",
      "@react-spectrum/inlinealert",
      "@react-spectrum/image",
      "@react-spectrum/label",
      "@react-spectrum/labeledvalue",
      "@react-spectrum/layout",
      "@react-spectrum/link",
      "@react-spectrum/list",
      "@react-spectrum/listbox",
      "@react-spectrum/menu",
      "@react-spectrum/meter",
      "@react-spectrum/numberfield",
      "@react-spectrum/overlays",
      "@react-spectrum/picker",
      "@react-spectrum/progress",
      "@react-spectrum/provider",
      "@react-spectrum/radio",
      "@react-spectrum/slider",
      "@react-spectrum/searchfield",
      "@react-spectrum/statuslight",
      "@react-spectrum/switch",
      "@react-spectrum/table",
      "@react-spectrum/tabs",
      "@react-spectrum/tag",
      "@react-spectrum/text",
      "@react-spectrum/textfield",
      "@react-spectrum/theme-dark",
      "@react-spectrum/theme-default",
      "@react-spectrum/theme-light",
      "@react-spectrum/tooltip",
      "@react-spectrum/toast",
      "@react-spectrum/view",
      "@react-spectrum/well",
      "@spectrum-icons/illustrations",
      "@spectrum-icons/ui",
      "@spectrum-icons/workflow",
    ],
  },
  plugins: [reactRouter(), tsconfigPaths()],
  resolve: {
    alias: {
      "@features": path.resolve(__dirname, "app/features"),
      "@bananagl": path.resolve(__dirname, "app/features/bananagl"),
      "@editor": path.resolve(__dirname, "app/features/editor"),
      "@core": path.resolve(__dirname, "app/core"),
    },
  },
});
