services:
    devcontainer:
        container_name: ${COMPOSE_PROJECT_NAME:-metacity-dev}-devcontainer
        build: .
        volumes:
            - ..:/workspace
                
    surrealdb:
        image: surrealdb/surrealdb:latest
        container_name: ${COMPOSE_PROJECT_NAME:-metacity-dev}-surrealdb
        restart: always
        command: start --log trace --username root --password root --auth
