name: Build

on:
  workflow_call:

jobs:
  build-studio:
    name: Build and push studio Docker image
    needs: test-studio
    uses: ./.github/workflows/studio-build.yml

  build-converter:
    name: Build and push coordinates converter Docker image
    needs: test-converter
    uses: ./.github/workflows/converter-build.yml
