name: Metacity Studio CI

on:
  push:
    branches:
      - dev
    paths:
      - "studio/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "studio/**"
      - ".github/workflows/ci.yml"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: pds
          POSTGRES_PASSWORD: pds-pass
          POSTGRES_DB: pds
      minio:
        image: bitnami/minio # using bitnami image because minio official image doesnt have command specified and github actions dont allow to specify
        ports:
          - 9000:9000
        environment:
          MINIO_VOLUMES: /data
          MINIO_ROOT_USER: pds
          MINIO_ROOT_PASSWORD: pdspdspds

    env:
      DB_HOST: localhost
      DB_USERNAME: pds
      DB_PASSWORD: pds-pass
      DB_DATABASE: pds
      MINIO_ENDPOINT: localhost
      MINIO_ACCESS_KEY: pds
      MINIO_SECRET_KEY: pdspdspds

    steps:
      - uses: actions/checkout@v3

      - name: "Setup Node.js"
        uses: "actions/setup-node@v3"
        with:
          node-version: 18

      - name: Install dependencies
        run: cd studio && npm ci

      - name: Run tests
        run: cd studio && npm test
