name: Metacity Studio Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build Docker image
    uses: ./.github/workflows/build.yml

  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Notify Watchtower using curl
        run: 'curl -I -H "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}" ${{ vars.WATCHTOWER_URL }}'
