name: Metacity Studio Build

on:
  workflow_call:

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the updated source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push it to the container registry
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./studio
          tags: "ghcr.io/metacitytools/studio:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
