name: Test all

on:
  workflow_call:

jobs:
  test-studio:
    name: Run studio tests
    uses: ./.github/workflows/studio-test.yml

  test-converter:
    name: Run coordinates converter tests
    uses: ./.github/workflows/converter-test.yml
