name: Test Coordinates Converter

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "coordinates_converter/**"
      - ".github/workflows/converter-test.yml"
  workflow_call:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          cd coordinates_converter
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd coordinates_converter/tests
          pytest -rA
